name: Deploy

on:
  workflow_dispatch:
    inputs:
      status:
        type: boolean

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Succeed
        if: ${{ github.event.inputs.status }}
        run: exit 0
      - name: Fail
        if: ${{ github.event.inputs.status }}
        run: exit 1
      - name: Build succeeded
        if: ${{ success() }}
        run: |
          python test.py Green
      - name: Build Failed
        if: ${{ failure() }}
        run: |
          python test.py Red


        #curl -k --location 'https://192.168.119.93/clip/v2/resource/device' --header 'hue-application-key: NbW6sDPFjLA1QoLTMd5MRb9a-wzFZBghWXt8wXdb'