name: Deploy

on:
  workflow_dispatch:
    inputs:
        payload:
          type: choice
          description: payload
          options:
            - 'On'
            - 'Off'

  #push:
  #  branches:
  #    - main

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Connection test
        run: |
          python test.py ${{ github.event.inputs.payload }}

        #curl -k --location 'https://192.168.119.93/clip/v2/resource/device' --header 'hue-application-key: NbW6sDPFjLA1QoLTMd5MRb9a-wzFZBghWXt8wXdb'