name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Connection test
        run:
          ./test.sh

        #curl -k --location 'https://192.168.119.93/clip/v2/resource/device' --header 'hue-application-key: NbW6sDPFjLA1QoLTMd5MRb9a-wzFZBghWXt8wXdb'